AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: air-traffic-tracker (serverless)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256

Resources:
  PlanesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: GET
        Planes:
          Type: Api
          Properties:
            Path: /planes
            Method: GET
        Track:
          Type: Api
          Properties:
            Path: /track
            Method: GET
Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL (Prod)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
